project_id = "yzlszvvhbcasbzsaastq"

[functions.ai-chat]
verify_jwt = false

[functions.gemini-voice]
verify_jwt = false

[functions.openai-realtime-session]
verify_jwt = false

[functions.process-session]
verify_jwt = false

[functions.thematic-diary-chat]
verify_jwt = false
